"""`deploy/verify_locked_runtime.py` 的負向測試。不需要 docker、不需要 image。

    uv run --with packaging python tests/test_locked_runtime.py

為什麼要有這支：這道閘的第一版**是假綠的**。它只比兩邊的交集，於是「這個套件整顆不見了」
跟「這個套件本來就不該在 linux 上」被壓成同一件事。實測拿掉整顆 Flask，它印
「對得上 23/23 個」然後 exit 0。

一道驗證器自己沒有被驗證過，就只是一句宣稱。所以這支測的重點不是「對的輸入會過」，
而是**每一種錯的輸入都要紅**，而且要紅在對的那一格。

⚠ 用合成的 fixture 不用真的 image：這支要能在沒有 docker 的環境跑（CI 的 claude-pty job
  就是那樣）。真 image 的那一份驗證在 workflow 的 deploy-image job，兩者互補。
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
VERIFIER = os.path.join(os.path.dirname(HERE), "deploy", "verify_locked_runtime.py")

_pass = _fail = 0


def check(label, ok):
    global _pass, _fail
    _pass += ok
    _fail += not ok
    print(f"  {'PASS' if ok else 'FAIL'}  {label}")


TMP = tempfile.mkdtemp(prefix="locked-runtime-")

# 目標環境固定成 linux/x86_64/cpython 3.13，跟 deploy image 一致。
# ⚠ 不用跑測試那台機器的環境：寫這支的時候在 macOS 上實測，`platform_machine` 是 `arm64`
#   而 greenlet 的 marker 只列到 `aarch64`，於是它被算成「不該裝」。marker 一定要用
#   **那顆 image** 的環境算，這也是 verifier 收第三個參數的理由。
ENV = os.path.join(TMP, "env.json")
with open(ENV, "w", encoding="utf-8") as fh:
    json.dump(
        {
            "sys_platform": "linux",
            "platform_machine": "x86_64",
            "platform_system": "Linux",
            "os_name": "posix",
            "python_version": "3.13",
            "python_full_version": "3.13.14",
            "implementation_name": "cpython",
            "platform_python_implementation": "CPython",
        },
        fh,
    )

# marker 三種都放：無條件、成立、不成立。build 工具也放一個。
LOCKED = """\
# This file was autogenerated by uv
flask==3.1.3 \\
    --hash=sha256:aaaa
gunicorn==26.0.0 \\
    --hash=sha256:bbbb
    # via claude-pty
greenlet==3.5.4 ; platform_machine == 'aarch64' or platform_machine == 'x86_64' \\
    --hash=sha256:cccc
pywin32==312 ; sys_platform == 'win32' \\
    --hash=sha256:dddd
setuptools==80.9.0 \\
    --hash=sha256:eeee
"""

# image 該有的樣子：無條件那兩個＋marker 成立的 greenlet，setuptools 被 pip uninstall 掉，
# pywin32 在 linux 上本來就不裝，專案自己是 `name @ url`。
GOOD = """\
Flask==3.1.3
gunicorn==26.0.0
greenlet==3.5.4
claude-pty @ file:///app
"""


def write(name: str, body: str) -> str:
    p = os.path.join(TMP, name)
    with open(p, "w", encoding="utf-8") as fh:
        fh.write(body)
    return p


def run(installed: str, locked: str = LOCKED, env: str | None = ENV) -> int:
    args = [sys.executable, VERIFIER, write(installed + ".txt", installed_body[installed]), write("locked.txt", locked)]
    if env:
        args.append(env)
    r = subprocess.run(args, capture_output=True, text=True, timeout=60)
    print("      " + (r.stdout + r.stderr).strip().replace("\n", "\n      ")[:400])
    return r.returncode


installed_body = {
    "good": GOOD,
    # 版本對不上
    "mismatch": GOOD.replace("Flask==3.1.3", "Flask==3.0.0"),
    # 無條件必要的套件整顆不見（舊版在這一格 exit 0）
    "missing": GOOD.replace("Flask==3.1.3\n", ""),
    # marker 成立的那顆不見（greenlet 在 linux/x86_64 上該裝）
    "missing_marker_true": GOOD.replace("greenlet==3.5.4\n", ""),
    # image 裡多一個 lockfile 沒有的
    "unexpected": GOOD + "requests==2.32.3\n",
    # 空的
    "empty": "",
    # 名稱大小寫與底線的正規化（Flask/flask、argon2_cffi/argon2-cffi）
    "canon": "flask==3.1.3\nGunicorn==26.0.0\ngreenlet==3.5.4\nclaude_pty @ file:///app\n",
    # 用 `pip install git+https://...` 之類的方式塞進來的東西，落地的形狀是 `name @ url`，
    # 沒有 `==`。它一樣繞過了 lockfile，一樣要紅。
    "unpinned_intruder": GOOD + "sneaky @ git+https://example.com/sneaky.git\n",
    # 必要套件從 `name==版本` 被換成 direct reference。人在、名字對，但版本驗不了。
    # 這一格是第二版自己造出來的洞（missing 的計算把整袋 unpinned 都扣掉），實測 exit 0。
    "required_became_unpinned": GOOD.replace("Flask==3.1.3", "Flask @ file:///tmp/flask"),
}

print("== 對的輸入要過 ==")
check("完全相符 → 0", run("good") == 0)
check("名稱大小寫／底線正規化之後也算相符 → 0", run("canon") == 0)

print("== 🔴 每一種錯都要紅，而且紅在對的那一格 ==")
check("版本對不上 → 非 0", run("mismatch") != 0)
check("🔴 無條件必要的套件整顆不見 → 非 0（舊版在這一格 exit 0）", run("missing") != 0)
check("marker 成立的套件不見 → 非 0", run("missing_marker_true") != 0)
check("image 裡多一個 lockfile 沒有的 → 非 0（policy 是失敗，不是印一行放行）", run("unexpected") != 0)
check("image 清單是空的 → 非 0（讀不到不等於通過）", run("empty") != 0)
check(
    "🔴 未釘版本的入侵者（`name @ url`）也要紅，不可以因為沒有 `==` 就被跳過",
    run("unpinned_intruder") != 0,
)
check(
    "🔴 必要套件被換成 direct reference（人在但版本驗不了）也要紅",
    run("required_became_unpinned") != 0,
)

print("== 合法缺席不可以誤報 ==")
# 這兩條是第一版那個「只比交集」的原始動機。動機沒錯，錯的是做法：
# 正確的做法是把它們各自講清楚，不是把整個比對放寬。
check("marker 不成立的（pywin32 在 linux）不算少 → 0", run("good") == 0)
check("build 工具（setuptools）被 pip uninstall 掉不算少 → 0", run("good") == 0)
check("專案自己（`claude-pty @ file:///app`）不算多 → 0", run("good") == 0)

print("== 🔴 marker 要用目標環境算，不是跑測試這台的 ==")
# 不帶 env 時用本機環境。在 macOS/arm64 上 greenlet 的 marker 不成立，於是 image 裡的
# greenlet 會被判成「多了」。這一條在 linux/x86_64 的 runner 上會是 0，在 macOS 上非 0，
# 所以不能斷言退出碼，只能斷言「兩者有可能不同」這件事被 env 參數處理掉了。
with_env = run("good", env=ENV)
check("帶了目標環境 → 0（這是 CI 的用法）", with_env == 0)

print("== lockfile 本身讀不到東西也要紅 ==")
check("lockfile 是空的 → 非 0", run("good", locked="# 只有註解\n") != 0)

print("== 參數數量不對 → 2（用法錯誤，與驗證失敗分開）==")
r = subprocess.run([sys.executable, VERIFIER], capture_output=True, text=True, timeout=60)
check("沒帶參數 → 2", r.returncode == 2)

shutil.rmtree(TMP, ignore_errors=True)

print(f"\n{_pass} passed, {_fail} failed")
sys.exit(1 if _fail else 0)
